### PR TITLE
Proposed newSession endpoint

### PR DESCRIPTION
**Pull request by bmeike**
My proposal for extending the /setupLogging endpoint as /newSession.

Of note:
- This will require a change to all of python tests.  I think it will be easy: each suite needs to start a session
- I don't think that the example given for the log slurper URL is actually a URL.  Should it be?
- One of the editors has removed all the extraneous spaces.  I suggest viewing difference with the &w=1 flag.

### CODE REVIEW

**Review by borrrden — APPROVED** [review]

**Comment by borrrden** [comment]
The example for the log slurper could possibly be changed to include a prefix but it would be different depending on the operations (some are http and some are ws)

**Review by borrrden — CHANGES_REQUESTED** [review]
https://github.com/couchbaselabs/couchbase-lite-tests/blob/main/spec/api/api.yaml#L108

Needs a bump to 0.6.0

**Comment by bmeike** [comment]
@borrrden : huh?  It is 0.6.0!!

**Comment by bmeike** [comment]
I see.  There is a comment for the version and the actual version.  FIxed

**Pull request merged**
